cursor            #dfb8f7
cursor_text_color #412356

foreground            #e9e0e8
background            #100d12
selection_foreground  #372c3f
selection_background  #d2c1d9
url_color             #d2c1d9

#: black 000000 767676
color0  #161217
color8  #383339
#: red cc0403 f2201f
color1  #231d47
color9  #5849b4
#: green 19cb00 23fd00
color2  #d2c1d9
color10 #efdcf5
#: yellow cecb00 fffd00
color3  #f4b7ba
color11 #ffdadb
#: blue 0d73cc 1a8fff
color4  #593a6f
color12 #dfb8f7
#: magenta cb1ed1 fd28ff
color5  #4f4256
color13 #d2c1d9
#: cyan 0dcdcd 14ffff
color6  #663b3e
color14 #f4b7ba
#: white dddddd ffffff
color7  #cdc3ce
color15 #e9e0e8

mark1_foreground #2a0c40
mark1_background #f3daff
mark2_foreground #221729
mark2_background #efdcf5
mark3_foreground #331014
mark3_background #ffdadb

active_tab_foreground #412356
active_tab_background #dfb8f7
inactive_tab_foreground #f3daff
inactive_tab_background #593a6f

active_border_color #dfb8f7
inactive_border_color #412356
# bell_border_color #ff5a00
