cursor            #91d5ad
cursor_text_color #003822

foreground            #dfe4dd
background            #0a0f0c
selection_foreground  #203529
selection_background  #b4ccbb
url_color             #b4ccbb

#: black 000000 767676
color0  #0f1511
color8  #303632
#: red cc0403 f2201f
color1  #455f6a
color9  #91acb7
#: green 19cb00 23fd00
color2  #b4ccbb
color10 #d0e8d7
#: yellow cecb00 fffd00
color3  #a4cddd
color11 #bfe9f9
#: blue 0d73cc 1a8fff
color4  #025233
color12 #91d5ad
#: magenta cb1ed1 fd28ff
color5  #364b3e
color13 #b4ccbb
#: cyan 0dcdcd 14ffff
color6  #234c59
color14 #a4cddd
#: white dddddd ffffff
color7  #c0c9c0
color15 #dfe4dd

mark1_foreground #002112
mark1_background #acf2c8
mark2_foreground #0b1f15
mark2_background #d0e8d7
mark3_foreground #001f28
mark3_background #bfe9f9

active_tab_foreground #003822
active_tab_background #91d5ad
inactive_tab_foreground #acf2c8
inactive_tab_background #025233

active_border_color #91d5ad
inactive_border_color #003822
# bell_border_color #ff5a00
