cursor            #f6b2e0
cursor_text_color #4e1e44

foreground            #ecdfe5
background            #120c10
selection_foreground  #3e2a38
selection_background  #dcbed0
url_color             #dcbed0

#: black 000000 767676
color0  #181215
color8  #3a3337
#: red cc0403 f2201f
color1  #344257
color9  #778dad
#: green 19cb00 23fd00
color2  #dcbed0
color10 #f9daec
#: yellow cecb00 fffd00
color3  #f5b9a2
color11 #ffdbce
#: blue 0d73cc 1a8fff
color4  #68355b
color12 #f6b2e0
#: magenta cb1ed1 fd28ff
color5  #56404f
color13 #dcbed0
#: cyan 0dcdcd 14ffff
color6  #663c2b
color14 #f5b9a2
#: white dddddd ffffff
color7  #d2c2ca
color15 #ecdfe5

mark1_foreground #35072e
mark1_background #ffd7ef
mark2_foreground #281623
mark2_background #f9daec
mark3_foreground #321205
mark3_background #ffdbce

active_tab_foreground #4e1e44
active_tab_background #f6b2e0
inactive_tab_foreground #ffd7ef
inactive_tab_background #68355b

active_border_color #f6b2e0
inactive_border_color #4e1e44
# bell_border_color #ff5a00
