$image = /home/dipan/.config/wall/a_river_running_through_a_valley.png

$background = rgba(131313ff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(313030ff)

$inverse_primary = rgba(595f61ff)

$inverse_surface = rgba(e5e2e1ff)

$on_background = rgba(e5e2e1ff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(2b3133ff)

$on_primary_container = rgba(000000ff)

$on_primary_fixed = rgba(171d1eff)

$on_primary_fixed_variant = rgba(42484aff)

$on_secondary = rgba(2f3131ff)

$on_secondary_container = rgba(e0e0e1ff)

$on_secondary_fixed = rgba(1a1c1dff)

$on_secondary_fixed_variant = rgba(454748ff)

$on_surface = rgba(e5e2e1ff)

$on_surface_variant = rgba(c3c7c8ff)

$on_tertiary = rgba(392e2aff)

$on_tertiary_container = rgba(000000ff)

$on_tertiary_fixed = rgba(231a15ff)

$on_tertiary_fixed_variant = rgba(50443fff)

$outline = rgba(8d9193ff)

$outline_variant = rgba(434749ff)

$primary = rgba(c2c7c9ff)

$primary_container = rgba(8c9294ff)

$primary_fixed = rgba(dee3e5ff)

$primary_fixed_dim = rgba(c2c7c9ff)

$scrim = rgba(000000ff)

$secondary = rgba(c6c6c7ff)

$secondary_container = rgba(454748ff)

$secondary_fixed = rgba(e2e2e3ff)

$secondary_fixed_dim = rgba(c6c6c7ff)

$shadow = rgba(000000ff)

$source_color = rgba(888e90ff)

$surface = rgba(131313ff)

$surface_bright = rgba(393939ff)

$surface_container = rgba(201f20ff)

$surface_container_high = rgba(2a2a2aff)

$surface_container_highest = rgba(353535ff)

$surface_container_low = rgba(1c1b1cff)

$surface_container_lowest = rgba(0e0e0eff)

$surface_dim = rgba(131313ff)

$surface_tint = rgba(c2c7c9ff)

$surface_variant = rgba(434749ff)

$tertiary = rgba(d4c3bcff)

$tertiary_container = rgba(9d8e88ff)

$tertiary_fixed = rgba(f1dfd8ff)

$tertiary_fixed_dim = rgba(d4c3bcff)

