$image = /home/dipan/.config/wall/b-032.jpg

$background = rgba(131313ff)

$error = rgba(ffb4abff)

$error_container = rgba(a7060fff)

$inverse_on_surface = rgba(303030ff)

$inverse_primary = rgba(5e5e5eff)

$inverse_surface = rgba(e2e2e2ff)

$on_background = rgba(e2e2e2ff)

$on_error = rgba(660004ff)

$on_error_container = rgba(ffffffff)

$on_primary = rgba(1b1b1bff)

$on_primary_container = rgba(000000ff)

$on_primary_fixed = rgba(ffffffff)

$on_primary_fixed_variant = rgba(f7f7f7ff)

$on_secondary = rgba(1b1b1bff)

$on_secondary_container = rgba(ffffffff)

$on_secondary_fixed = rgba(161616ff)

$on_secondary_fixed_variant = rgba(393939ff)

$on_surface = rgba(e2e2e2ff)

$on_surface_variant = rgba(c6c6c6ff)

$on_tertiary = rgba(1b1b1bff)

$on_tertiary_container = rgba(000000ff)

$on_tertiary_fixed = rgba(ffffffff)

$on_tertiary_fixed_variant = rgba(f7f7f7ff)

$outline = rgba(919191ff)

$outline_variant = rgba(525252ff)

$primary = rgba(ffffffff)

$primary_container = rgba(d4d4d4ff)

$primary_fixed = rgba(6a6a6aff)

$primary_fixed_dim = rgba(525252ff)

$scrim = rgba(000000ff)

$secondary = rgba(c6c6c6ff)

$secondary_container = rgba(525252ff)

$secondary_fixed = rgba(c6c6c6ff)

$secondary_fixed_dim = rgba(abababff)

$shadow = rgba(000000ff)

$source_color = rgba(574245ff)

$surface = rgba(131313ff)

$surface_bright = rgba(3b3b3bff)

$surface_container = rgba(212121ff)

$surface_container_high = rgba(2c2c2cff)

$surface_container_highest = rgba(363636ff)

$surface_container_low = rgba(1c1c1cff)

$surface_container_lowest = rgba(0d0d0dff)

$surface_dim = rgba(131313ff)

$surface_tint = rgba(c6c6c6ff)

$surface_variant = rgba(474747ff)

$tertiary = rgba(e2e2e2ff)

$tertiary_container = rgba(919191ff)

$tertiary_fixed = rgba(6a6a6aff)

$tertiary_fixed_dim = rgba(525252ff)

