$image = /home/dipan/.config/wall/b-917.jpg

$background = rgba(131313ff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(313030ff)

$inverse_primary = rgba(5a5f63ff)

$inverse_surface = rgba(e5e2e1ff)

$on_background = rgba(e5e2e1ff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(2c3134ff)

$on_primary_container = rgba(41464aff)

$on_primary_fixed = rgba(171c1fff)

$on_primary_fixed_variant = rgba(42484bff)

$on_secondary = rgba(2f3132ff)

$on_secondary_container = rgba(e8e8e9ff)

$on_secondary_fixed = rgba(1a1c1dff)

$on_secondary_fixed_variant = rgba(454748ff)

$on_surface = rgba(e5e2e1ff)

$on_surface_variant = rgba(c4c7c9ff)

$on_tertiary = rgba(392e29ff)

$on_tertiary_container = rgba(4f433dff)

$on_tertiary_fixed = rgba(231a15ff)

$on_tertiary_fixed_variant = rgba(50443fff)

$outline = rgba(8e9194ff)

$outline_variant = rgba(44474aff)

$primary = rgba(f7fbffff)

$primary_container = rgba(dadfe3ff)

$primary_fixed = rgba(dee3e7ff)

$primary_fixed_dim = rgba(c2c7cbff)

$scrim = rgba(000000ff)

$secondary = rgba(c6c6c8ff)

$secondary_container = rgba(4a4c4dff)

$secondary_fixed = rgba(e2e2e4ff)

$secondary_fixed_dim = rgba(c6c6c8ff)

$shadow = rgba(000000ff)

$source_color = rgba(dadfe3ff)

$surface = rgba(131313ff)

$surface_bright = rgba(393939ff)

$surface_container = rgba(201f20ff)

$surface_container_high = rgba(2a2a2aff)

$surface_container_highest = rgba(353535ff)

$surface_container_low = rgba(1c1b1cff)

$surface_container_lowest = rgba(0e0e0eff)

$surface_dim = rgba(131313ff)

$surface_tint = rgba(c2c7cbff)

$surface_variant = rgba(44474aff)

$tertiary = rgba(fffaf9ff)

$tertiary_container = rgba(eddbd3ff)

$tertiary_fixed = rgba(f1dfd7ff)

$tertiary_fixed_dim = rgba(d4c3bbff)

