###################
### KEYBINDINGS ###
###################

$mainMod = SUPER

bind = $mainMod, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit

bind = $mainMod, V, togglefloating,
bind = $mainMod, F, fullscreen, 0
bind = $mainMod, P, pseudo,

# Move focus with SUPER + hjkl (vim style)
bind = $mainMod, h, movefocus, l
bind = $mainMod, l, movefocus, r
bind = $mainMod, k, movefocus, u
bind = $mainMod, j, movefocus, d


# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

bind = $mainMod, semicolon, resizeactive, -50 0
bind = $mainMod, apostrophe, resizeactive, 50 0

# Apps
bind = $mainMod, T, exec, kitty
bind = $mainMod, B, exec, chromium
bind = $mainMod, E, exec, nautilus

# Kill window
bind = $mainMod, Q, killactive

# Move window to workspace
bind = $mainMod SHIFT, left, movetoworkspace, -1
bind = $mainMod SHIFT, right, movetoworkspace, +1
bind = $mainMod SHIFT, up, movetoworkspace, e+1
bind = $mainMod SHIFT, down, movetoworkspace, e-1

# Special workspace (scratchpad)
bind = $mainMod, S, togglespecialworkspace, magic
bind = $mainMod SHIFT, S, movetoworkspace, special:magic

# Scroll through workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# Laptop multimedia keys for volume and LCD brightness
bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = ,XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 5%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 5%-

# Requires playerctl
bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPause, exec, playerctl play-pause
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioPrev, exec, playerctl previous

# Quickshell keybindings
bind = SUPER, W, global, quickshell:wallpaperToggle
bind = SUPER, Tab, global, quickshell:launcherToggle
bind = SUPER, Escape, global, quickshell:powerMenuToggle
bind = SUPER, Escape, exec, hyprlock
bind = SUPER, Print, exec, hyprshot -m region --raw | satty --filename -
bind = SUPER, F11, exec, hyprshot -m region --raw | satty --filename -


bind = $mainMod ALT, left,  swapwindow, l
bind = $mainMod ALT, right, swapwindow, r
bind = $mainMod ALT, up,    swapwindow, u
bind = $mainMod ALT, down,  swapwindow, d
