# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#e5e2e1"

# Title color for boxes
theme[title]="#f7fbff"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#c6c6c8"

# Background color of selected item in processes box
theme[selected_bg]="#f7fbff"

# Foreground color of selected item in processes box
theme[selected_fg]="#2c3134"

# Color of inactive/disabled text
theme[inactive_fg]="#c4c7c9"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#fffaf9"

# Cpu box outline color
theme[cpu_box]="#8e9194"

# Memory/disks box outline color
theme[mem_box]="#8e9194"

# Net up/down box outline color
theme[net_box]="#8e9194"

# Processes box outline color
theme[proc_box]="#8e9194"

# Box divider line and small boxes line color
theme[div_line]="#44474a"

# Temperature graph colors
theme[temp_start]="#c6c6c8"
theme[temp_mid]="#f7fbff"
theme[temp_end]="#ffb4ab"

# CPU graph colors
theme[cpu_start]="#c6c6c8"
theme[cpu_mid]="#f7fbff"
theme[cpu_end]="#ffb4ab"

# Mem/Disk free meter
theme[free_start]="#c6c6c8"
theme[free_mid]=""
theme[free_end]="#4a4c4d"

# Mem/Disk cached meter
theme[cached_start]="#fffaf9"
theme[cached_mid]=""
theme[cached_end]="#eddbd3"

# Mem/Disk available meter
theme[available_start]="#f7fbff"
theme[available_mid]=""
theme[available_end]="#dadfe3"

# Mem/Disk used meter
theme[used_start]="#ffb4ab"
theme[used_mid]=""
theme[used_end]="#93000a"

# Download graph colors
theme[download_start]="#c6c6c8"
theme[download_mid]="#f7fbff"
theme[download_end]="#fffaf9"

# Upload graph colors
theme[upload_start]="#c6c6c8"
theme[upload_mid]="#f7fbff"
theme[upload_end]="#fffaf9"
