# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#e5e2e1"

# Title color for boxes
theme[title]="#c2c7c9"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#c6c6c7"

# Background color of selected item in processes box
theme[selected_bg]="#c2c7c9"

# Foreground color of selected item in processes box
theme[selected_fg]="#2b3133"

# Color of inactive/disabled text
theme[inactive_fg]="#c3c7c8"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#d4c3bc"

# Cpu box outline color
theme[cpu_box]="#8d9193"

# Memory/disks box outline color
theme[mem_box]="#8d9193"

# Net up/down box outline color
theme[net_box]="#8d9193"

# Processes box outline color
theme[proc_box]="#8d9193"

# Box divider line and small boxes line color
theme[div_line]="#434749"

# Temperature graph colors
theme[temp_start]="#c6c6c7"
theme[temp_mid]="#c2c7c9"
theme[temp_end]="#ffb4ab"

# CPU graph colors
theme[cpu_start]="#c6c6c7"
theme[cpu_mid]="#c2c7c9"
theme[cpu_end]="#ffb4ab"

# Mem/Disk free meter
theme[free_start]="#c6c6c7"
theme[free_mid]=""
theme[free_end]="#454748"

# Mem/Disk cached meter
theme[cached_start]="#d4c3bc"
theme[cached_mid]=""
theme[cached_end]="#9d8e88"

# Mem/Disk available meter
theme[available_start]="#c2c7c9"
theme[available_mid]=""
theme[available_end]="#8c9294"

# Mem/Disk used meter
theme[used_start]="#ffb4ab"
theme[used_mid]=""
theme[used_end]="#93000a"

# Download graph colors
theme[download_start]="#c6c6c7"
theme[download_mid]="#c2c7c9"
theme[download_end]="#d4c3bc"

# Upload graph colors
theme[upload_start]="#c6c6c7"
theme[upload_mid]="#c2c7c9"
theme[upload_end]="#d4c3bc"
