cursor            #b3cad9
cursor_text_color #1e333f

foreground            #e3e2e3
background            #0d0e0f
selection_foreground  #2a3137
selection_background  #c0c7ce
url_color             #c0c7ce

#: black 000000 767676
color0  #121314
color8  #343536
#: red cc0403 f2201f
color1  #1e262a
color9  #5d7684
#: green 19cb00 23fd00
color2  #c0c7ce
color10 #dce3ea
#: yellow cecb00 fffd00
color3  #e1c19f
color11 #feddb9
#: blue 0d73cc 1a8fff
color4  #354956
color12 #b3cad9
#: magenta cb1ed1 fd28ff
color5  #40484d
color13 #c0c7ce
#: cyan 0dcdcd 14ffff
color6  #594328
color14 #e1c19f
#: white dddddd ffffff
color7  #c3c7cb
color15 #e3e2e3

mark1_foreground #071e29
mark1_background #cfe6f5
mark2_foreground #151d21
mark2_background #dce3ea
mark3_foreground #291803
mark3_background #feddb9

active_tab_foreground #1e333f
active_tab_background #b3cad9
inactive_tab_foreground #ffffff
inactive_tab_background #4b606d

active_border_color #b3cad9
inactive_border_color #1e333f
# bell_border_color #ff5a00
