cursor            #c2c7c9
cursor_text_color #2b3133

foreground            #e5e2e1
background            #0e0e0e
selection_foreground  #2f3131
selection_background  #c6c6c7
url_color             #c6c6c7

#: black 000000 767676
color0  #131313
color8  #353535
#: red cc0403 f2201f
color1  #1e262a
color9  #5d7684
#: green 19cb00 23fd00
color2  #c6c6c7
color10 #e2e2e3
#: yellow cecb00 fffd00
color3  #d4c3bc
color11 #f1dfd8
#: blue 0d73cc 1a8fff
color4  #42484a
color12 #c2c7c9
#: magenta cb1ed1 fd28ff
color5  #454748
color13 #c6c6c7
#: cyan 0dcdcd 14ffff
color6  #50443f
color14 #d4c3bc
#: white dddddd ffffff
color7  #c3c7c8
color15 #e5e2e1

mark1_foreground #171d1e
mark1_background #dee3e5
mark2_foreground #1a1c1d
mark2_background #e2e2e3
mark3_foreground #231a15
mark3_background #f1dfd8

active_tab_foreground #2b3133
active_tab_background #c2c7c9
inactive_tab_foreground #000000
inactive_tab_background #8c9294

active_border_color #c2c7c9
inactive_border_color #2b3133
# bell_border_color #ff5a00
