cursor            #f7fbff
cursor_text_color #2c3134

foreground            #e5e2e1
background            #0e0e0e
selection_foreground  #2f3132
selection_background  #c6c6c8
url_color             #c6c6c8

#: black 000000 767676
color0  #131313
color8  #353535
#: red cc0403 f2201f
color1  #212931
color9  #5f748c
#: green 19cb00 23fd00
color2  #c6c6c8
color10 #e2e2e4
#: yellow cecb00 fffd00
color3  #d4c3bb
color11 #f1dfd7
#: blue 0d73cc 1a8fff
color4  #42484b
color12 #f7fbff
#: magenta cb1ed1 fd28ff
color5  #454748
color13 #c6c6c8
#: cyan 0dcdcd 14ffff
color6  #50443f
color14 #fffaf9
#: white dddddd ffffff
color7  #c4c7c9
color15 #e5e2e1

mark1_foreground #171c1f
mark1_background #dee3e7
mark2_foreground #1a1c1d
mark2_background #e2e2e4
mark3_foreground #231a15
mark3_background #f1dfd7

active_tab_foreground #2c3134
active_tab_background #f7fbff
inactive_tab_foreground #41464a
inactive_tab_background #dadfe3

active_border_color #f7fbff
inactive_border_color #2c3134
# bell_border_color #ff5a00
